server:
  port: 28088

spring:
  application:
    name: game-spring-cloud-job
  datasource:
    url: jdbc:mysql://njreader.rwlb.rds.aliyuncs.com:3306/db_game?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: game_prod
    password: dopDbEsA4rNQssE1@
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: set names utf8mb4;
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      max-lifetime: 120000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 20
        max-wait: 1000ms
        min-idle: 2
        max-active: 512
  session:
    store-type: redis
    timeout: 1800000 # 0.5h
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #    date-format: yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT+8
  serialization:
    fail_on_empty_beans: false
  mvc:
    favicon:
      enabled: false

logging:
  level:
    root: INFO
  config: classpath:logback.xml

gameFlow:
  thread:
    max: 64
    default: 8
  job:
    enable: false
  workspace: /root/logs
  bloomfilter:
    capacity: 1000000
    error-rate: 0.0001
  detect:
    dead-cycle: 5000

xxl:
  job:
    accessToken:  # 调度中心通讯TOKEN [选填]：非空时启用；
    i18n: zh_CN # 调度中心国际化配置 [必填]： 默认为 "zh_CN"/中文简体, 可选范围为 "zh_CN"/中文简体, "zh_TC"/中文繁体 and "en"/英文；
    triggerpool:  # 调度线程池最大线程配置【必填】
      fast:
        max: 200
      slow:
        max: 100
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: game-xxl-job-executor
      address:
      ip:
      port: 29999
      logpath: ./data/applogs/xxl-job/jobhandler
      logretentiondays: 30 # 调度中心日志表数据保存天数 [必填]：过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能；



