server:
  port: 18088
  servlet:
    context-path: /lotto

spring:
  application:
    name: game-spring-cloud-web
  datasource:
    url: jdbc:mysql://njreader.rwlb.rds.aliyuncs.com:3306/db_game?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: game_prod
    password: dopDbEsA4rNQssE1@
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: set names utf8mb4;
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      max-lifetime: 120000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 20
        max-wait: 1000ms
        min-idle: 2
        max-active: 512
  session:
    store-type: redis
    timeout: 1800000 # 0.5h
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  serialization:
    fail_on_empty_beans: false
  mvc:
    favicon:
      enabled: false

logging:
  level:
    root: DEBUG
  config: classpath:logback-product.xml

gameFlow:
  thread:
    max: 64
    default: 8
  job:
    enable: false
  workspace: /root/logs
  bloomfilter:
    capacity: 1000000
    error-rate: 0.0001
  detect:
    dead-cycle: 5000

swagger:
  production: false
  basic:
    enable: true
    username: test
    password: UKDFidU712hNklS08PffnB$Ds