server:
  port: 18088
  servlet:
    context-path: /lotto

spring:
  application:
    name: game-spring-cloud-web
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_game?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: root
    password: root123456
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: set names utf8mb4;
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      max-lifetime: 120000
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 20
        max-wait: 1000ms
        min-idle: 2
        max-active: 512
  session:
    store-type: redis
    timeout: 1800000 # 0.5h
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  serialization:
    fail_on_empty_beans: false
  mvc:
    favicon:
      enabled: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            #instanceName: clusteredScheduler #quartzScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            tablePrefix: qrtz_
            misfireThreshold: 60000 #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为60000（60秒）。
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

logging:
  level:
    root: INFO
  config: classpath:logback-develop.xml

gameFlow:
  thread:
    max: 64
    default: 8
  job:
    enable: false
  workspace: ./root/logs
  bloomfilter:
    capacity: 1000000
    error-rate: 0.0001
  detect:
    dead-cycle: 5000

swagger:
  production: false
  basic:
    enable: false
    username: test
    password: UKDFidU712hNklS08PffnB$Ds